services:
  traefik:
    image: "traefik:v3.3"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contato@emershow.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.http.redirections.entryPoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - "/var/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
  db:
    image: mysql
    env_file:
      - ./db.env
    ports:
      - 3306:3306
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - /var/redis:/var/run
    ports:
      - 6379:6379
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      timeout: 5s
      retries: 20

  ellaapi:
    image: ghcr.io/application-ellas/api:vbeta0.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ellaapi.loadbalancer.server.port=8080"
      - "traefik.http.routers.ellaapi.rule=Host(`api.emershow.com`)"
      - "traefik.http.routers.ellaapi.entrypoints=websecure"
      - "traefik.http.routers.ellaapi.tls.certresolver=myresolver"
    env_file:
      - ./api.env
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/app
    networks:
      - public
      - db-network
      - cache-network
    depends_on: 
      - db
      - cache
    
networks:
  cache-network:
    driver: overlay
  db-network:
    driver: overlay
  public:
    driver: overlay
