services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contato@emershow.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public
  db:
    image: mysql
    restart: always
    container_name: ellas-mysql
    env_file:
      - ./db.env
    ports:
      - 3306:3306
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ../data/mysql:/var/lib/mysql # use this to dev local volume
      - /var/lib/mysql:/var/lib/mysql # use this to prd local volume
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis
    container_name: ellas-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      # - ../data/redis:/var/run # use this to dev local volume
      - /var/redis:/var/run # use this to prd local volume
    ports:
      - 6379:6379
    restart: always
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      timeout: 5s
      retries: 20

  ellasapi:
    build: ./
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ellasapi.rule=Host(`emershow.com`)"
      - "traefik.http.routers.ellasapi.entrypoints=websecure"
      - "traefik.http.routers.ellasapi.tls.certresolver=myresolver"
    restart: always
    env_file:
      - ./api.env
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - .:/app
    networks:
      - public
      - db-network
      - cache-network
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

networks:
  cache-network:
    driver: bridge
  db-network:
    driver: bridge
  public:
    driver: bridge
