services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contato@emershow.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.http.redirections.entryPoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - "/var/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public

  db:
    image: mysql:9.2.0
    environment:
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    secrets:
      - mysql_user
      - mysql_password
      - mysql_root_password
      - mysql_database
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis:7.4.2
    command: redis-server --requirepass "$$(cat /run/secrets/redis_password)" --port 6379 --loglevel warning --save 60 1 --maxclients 1000 --maxmemory 1gb
    volumes:
      - /var/redis:/var/run
    ports:
      - 6379:6379
    networks:
      - cache-network
    secrets:
      - redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      timeout: 5s
      retries: 20

  ellaapi:
    image: ghcr.io/application-ellas/ella-api:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ellaapi.loadbalancer.server.port=8080"
      - "traefik.http.routers.ellaapi.rule=Host(`api.emershow.com`)"
      - "traefik.http.routers.ellaapi.entrypoints=websecure"
      - "traefik.http.routers.ellaapi.tls.certresolver=myresolver"
    env_file:
      - ./api.env
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 2
    volumes:
      - .:/app
    networks:
      - public
      - db-network
      - cache-network
    depends_on:
      - db
      - cache

networks:
  cache-network:
    driver: overlay
  db-network:
    driver: overlay
  public:
    driver: overlay

secrets:
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_root_password:
    external: true
  mysql_database:
    external: true
  redis_password:
    external: true
