services:
  traefik:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contato@emershow.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.websecure.http.redirections.entryPoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - public

  db:
    image: mysql:9.2.0
    secrets:
      - mysql_user
      - mysql_password
      - mysql_root_password
    environment:
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=ella-db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis:7.4.2
    secrets:
      - redis_password
    command:  bash -c 'redis-server --requirepass "$$(cat /run/secrets/redis_password)" --port 6379 --loglevel warning --save 60 1 --maxclients 1000 --maxmemory 1gb'
    ports:
      - 6379:6379
    volumes:
      - cache-data:/var/run
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      timeout: 5s
      retries: 20

  ellaapi:
    image: ghcr.io/application-ellas/ella-api:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ellaapi.loadbalancer.server.port=8080"
      - "traefik.http.routers.ellaapi.rule=Host(`api.emershow.com`)"
      - "traefik.http.routers.ellaapi.entrypoints=websecure"
      - "traefik.http.routers.ellaapi.tls.certresolver=myresolver"
    secrets:
      - api_mysql_user
      - api_mysql_password
      - api_redis_user
      - api_redis_password
      - google_client_id
      - google_client_secret
      - mercado_pago_token
      - jwt_secret_token
    environment:
      - DB_USER=/run/secrets/api_mysql_user
      - DB_PASS=/run/secrets/api_mysql_password
      - REDIS_USER=/run/secrets/api_redis_user
      - REDIS_PASSWORD=/run/secrets/api_redis_password
      - GOOGLE_CLIENT_ID=/run/secrets/google_client_id
      - GOOGLE_CLIENT_SECRET=/run/secrets/google_client_secret
      - MERCADO_PAGO_TOKEN=/run/secrets/mercado_pago_token
      - JWT_SECRET_KEY=/run/secrets/jwt_secret_token
      - GOOGLE_REDIRECT_URL=https://api.emershow.com/auth/callback/google
      - DB_HOST=db:3306
      - DB_NAME=ella-db
      - SERVER_PORT=8080
      - REDIS_HOST=cache:6379
      - FRONTEND_URL=http://localhost:3000/
      - AWS_DEFAULT_REGION=sa-east-1
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 2
    ports:
      - 8080:8080
    networks:
      - public
      - db-network
      - cache-network
    depends_on:
      - db
      - cache

networks:
  cache-network:
    driver: overlay
  db-network:
    driver: overlay
  public:
    driver: overlay

volumes:
  letsencrypt:
  db-data:
  cache-data:

secrets:
  mysql_user:
    external: true
  mysql_password:
    external: true
  mysql_root_password:
    external: true
  redis_password:
    external: true
  api_mysql_user:
    external: true
  api_mysql_password:
    external: true
  google_client_id:
    external: true
  google_client_secret:
    external: true
  mercado_pago_token:
    external: true
  jwt_secret_token:
    external: true
  api_redis_user:
    external: true
  api_redis_password:
    external: true
