services:
  db:
    image: mysql:9.2.0
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=boilerplate-db
    ports:
      - 3306:3306
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - ../data/mysql:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis:7.4.2
    command: redis-server --requirepass "development" --port 6379 --loglevel warning --save 60 1 --maxclients 1000 --maxmemory 1gb
    ports:
      - 6379:6379
    volumes:
      - ../data/redis:/var/run
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      start_period: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ENV=development
      - DB_USER=boilerplate-api
      - DB_PASS=password
      - REDIS_USER=boilerplate-api
      - REDIS_PASSWORD=password
      - GOOGLE_CLIENT_ID=14302173819-3rfe2jq2ptfg53njtvmrgtmhlqom435a.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - MERCADO_PAGO_TOKEN=TEST-2332090575580034-111111-2b4a678d9a00053264d90a30dbd2aac0-494198267
      - JWT_SECRET_KEY=mock-jwt-token
      - GOOGLE_REDIRECT_URL=https://localhost/auth/callback/google
      - DB_HOST=db:3306
      - DB_NAME=boilerplate-db
      - SERVER_PORT=8080
      - REDIS_HOST=cache:6379
      - FRONTEND_URL=http://localhost:3000/
      - AWS_DEFAULT_REGION=sa-east-1
    deploy:
      update_config:
        order: start-first
    ports:
      - 8080:8080
    networks:
      - db-network
      - cache-network
    depends_on:
      - db
      - cache

networks:
  cache-network:
  db-network:
