http:
    routers:
        portainer:
            rule: Host(`portainer.emershow.com`)
            tls:
                certResolver: lets-encrypt
            service: portainer
        api:
            rule: Host(`api.emershow.com`)
            tls:
                certResolver: lets-encrypt
            service: api
