http:
  routers:
    api:
      rule: Host(`api.emershow.com`)
      tls:
        certResolver: lets-encrypt
      service: api

    portainer:
      rule: Host(`portainer.emershow.com`)
      tls: {}
      service: portainer
