apiVersion: v1
kind: Service
metadata:
  name: boilerplate-api-service
spec:
  type: LoadBalancer
  selector:
    app: boilerplate-api
  ports:
  - port: 8080
    targetPort: api-port
    protocol: TCP
