name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Install dependencies
        run: go get ./...
      - name: Test with the Go CLI
        run: go test ./...

  build-and-push-image:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/application-ellas/ella-api:latest
            ghcr.io/application-ellas/ella-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Create Secrets
        run: |
          docker secret create mysql_user ${{ secrets.MYSQL_USER }}
          docker secret create mysql_password ${{ secrets.MYSQL_PASSWORD }}
          docker secret create mysql_root_password ${{ secrets.MYSQL_ROOT_PASSWORD }}
          docker secret create mysql_database ${{ secrets.MYSQL_DATABASE }}
          docker secret create mysql_host ${{ secrets.MYSQL_HOST }}
          docker secret create redis_password ${{ secrets.REDIS_REQUIRED_PASSWORD }}

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ella-backend
          file: docker-stack.prd.yml
          host: emershow.com
          user: github-actions-deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
